name: Instant Merge Konflux PRs

on:
  pull_request:
    types:
      - opened
    paths:
      - hack/metadata.env

permissions:
  contents: write
  pull-requests: write
  checks: write
  security-events: write
  statuses: write

jobs:
  instant-merge:
    runs-on: ubuntu-latest
    steps:
      - id: poc
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo ${{ github.event.sender.id }}
          echo ${{ github.event.sender.login }}
          echo "${{ github.event.pull_request.title }}"
          
      - name: instant-merge
        if: "${{ github.event.sender.login == 'red-hat-konflux[bot]' && startsWith(github.event.pull_request.title, 'chore(deps): update must-gather') }}"
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh pr merge --merge --admin ${{ github.event.pull_request.html_url }}
